project_id = "wgnbrncyobrkbkndqzcv"

[functions.scrape-lounges]
verify_jwt = false

[functions.discover-cities]
verify_jwt = false

[functions.search-places]
verify_jwt = false

[functions.generate-city-images]
verify_jwt = false

[functions.fetch-city-images]
verify_jwt = false
